// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CinemaAbyss API
 *
 * API спецификация для системы CinemaAbyss, включающая монолит и микросервисы.  Система CinemaAbyss представляет собой платформу для управления фильмами, пользователями, платежами и подписками. Архитектура системы включает монолитное приложение и выделенные микросервисы. 
 *
 * API version: 1.0.0
 * Contact: support@cinemaabyss.com
 */

package openapi

import (
	"context"
	"net/http"
)



// EventsAPIRouter defines the required methods for binding the api requests to a responses for the EventsAPI
// The EventsAPIRouter implementation should parse necessary information from the http request,
// pass the data to a EventsAPIServicer to perform the required actions, then write the service results to the http response.
type EventsAPIRouter interface { 
	CreateMovieEvent(http.ResponseWriter, *http.Request)
	CreateUserEvent(http.ResponseWriter, *http.Request)
	CreatePaymentEvent(http.ResponseWriter, *http.Request)
}
// HealthAPIRouter defines the required methods for binding the api requests to a responses for the HealthAPI
// The HealthAPIRouter implementation should parse necessary information from the http request,
// pass the data to a HealthAPIServicer to perform the required actions, then write the service results to the http response.
type HealthAPIRouter interface { 
	GetProxyHealth(http.ResponseWriter, *http.Request)
	GetMoviesServiceHealth(http.ResponseWriter, *http.Request)
	GetEventsServiceHealth(http.ResponseWriter, *http.Request)
}
// MoviesAPIRouter defines the required methods for binding the api requests to a responses for the MoviesAPI
// The MoviesAPIRouter implementation should parse necessary information from the http request,
// pass the data to a MoviesAPIServicer to perform the required actions, then write the service results to the http response.
type MoviesAPIRouter interface { 
	GetAllMovies(http.ResponseWriter, *http.Request)
	CreateMovie(http.ResponseWriter, *http.Request)
}
// PaymentsAPIRouter defines the required methods for binding the api requests to a responses for the PaymentsAPI
// The PaymentsAPIRouter implementation should parse necessary information from the http request,
// pass the data to a PaymentsAPIServicer to perform the required actions, then write the service results to the http response.
type PaymentsAPIRouter interface { 
	GetAllPayments(http.ResponseWriter, *http.Request)
	CreatePayment(http.ResponseWriter, *http.Request)
}
// SubscriptionsAPIRouter defines the required methods for binding the api requests to a responses for the SubscriptionsAPI
// The SubscriptionsAPIRouter implementation should parse necessary information from the http request,
// pass the data to a SubscriptionsAPIServicer to perform the required actions, then write the service results to the http response.
type SubscriptionsAPIRouter interface { 
	GetAllSubscriptions(http.ResponseWriter, *http.Request)
	CreateSubscription(http.ResponseWriter, *http.Request)
}
// UsersAPIRouter defines the required methods for binding the api requests to a responses for the UsersAPI
// The UsersAPIRouter implementation should parse necessary information from the http request,
// pass the data to a UsersAPIServicer to perform the required actions, then write the service results to the http response.
type UsersAPIRouter interface { 
	GetAllUsers(http.ResponseWriter, *http.Request)
	CreateUser(http.ResponseWriter, *http.Request)
}


// EventsAPIServicer defines the api actions for the EventsAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type EventsAPIServicer interface { 
	CreateMovieEvent(context.Context, MovieEvent) (ImplResponse, error)
	CreateUserEvent(context.Context, UserEvent) (ImplResponse, error)
	CreatePaymentEvent(context.Context, PaymentEvent) (ImplResponse, error)
}


// HealthAPIServicer defines the api actions for the HealthAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type HealthAPIServicer interface { 
	GetProxyHealth(context.Context) (ImplResponse, error)
	GetMoviesServiceHealth(context.Context) (ImplResponse, error)
	GetEventsServiceHealth(context.Context) (ImplResponse, error)
}


// MoviesAPIServicer defines the api actions for the MoviesAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type MoviesAPIServicer interface { 
	GetAllMovies(context.Context) (ImplResponse, error)
	CreateMovie(context.Context, MovieInput) (ImplResponse, error)
}


// PaymentsAPIServicer defines the api actions for the PaymentsAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type PaymentsAPIServicer interface { 
	GetAllPayments(context.Context, int32) (ImplResponse, error)
	CreatePayment(context.Context, PaymentInput) (ImplResponse, error)
}


// SubscriptionsAPIServicer defines the api actions for the SubscriptionsAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type SubscriptionsAPIServicer interface { 
	GetAllSubscriptions(context.Context, int32) (ImplResponse, error)
	CreateSubscription(context.Context, SubscriptionInput) (ImplResponse, error)
}


// UsersAPIServicer defines the api actions for the UsersAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type UsersAPIServicer interface { 
	GetAllUsers(context.Context) (ImplResponse, error)
	CreateUser(context.Context, UserInput) (ImplResponse, error)
}
