// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CinemaAbyss API
 *
 * API спецификация для системы CinemaAbyss, включающая монолит и микросервисы.  Система CinemaAbyss представляет собой платформу для управления фильмами, пользователями, платежами и подписками. Архитектура системы включает монолитное приложение и выделенные микросервисы.
 *
 * API version: 1.0.0
 * Contact: support@cinemaabyss.com
 */

package openapi

import (
	"context"
	"encoding/json"
	"net/http"
	"strings"
)

// PaymentsAPIController binds http requests to an api service and writes the service results to the http response
type PaymentsAPIController struct {
	service      PaymentsAPIServicer
	errorHandler ErrorHandler
}

// PaymentsAPIOption for how the controller is set up.
type PaymentsAPIOption func(*PaymentsAPIController)

// WithPaymentsAPIErrorHandler inject ErrorHandler into controller
func WithPaymentsAPIErrorHandler(h ErrorHandler) PaymentsAPIOption {
	return func(c *PaymentsAPIController) {
		c.errorHandler = h
	}
}

// NewPaymentsAPIController creates a default api controller
func NewPaymentsAPIController(s PaymentsAPIServicer, opts ...PaymentsAPIOption) *PaymentsAPIController {
	controller := &PaymentsAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the PaymentsAPIController
func (c *PaymentsAPIController) Routes() Routes {
	return Routes{
		"GetAllPayments": Route{
			"GetAllPayments",
			strings.ToUpper("Get"),
			"/api/payments",
			c.GetAllPayments,
		},
		"CreatePayment": Route{
			"CreatePayment",
			strings.ToUpper("Post"),
			"/api/payments",
			c.CreatePayment,
		},
	}
}

// OrderedRoutes returns all the api routes in a deterministic order for the PaymentsAPIController
func (c *PaymentsAPIController) OrderedRoutes() []Route {
	return []Route{
		Route{
			"GetAllPayments",
			strings.ToUpper("Get"),
			"/api/payments",
			c.GetAllPayments,
		},
		Route{
			"CreatePayment",
			strings.ToUpper("Post"),
			"/api/payments",
			c.CreatePayment,
		},
	}
}

// GetAllPayments - Получение списка всех платежей
func (c *PaymentsAPIController) GetAllPayments(w http.ResponseWriter, r *http.Request) {
	query, err := parseQuery(r.URL.RawQuery)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	var userIdParam int32
	if query.Has("user_id") {
		param, err := parseNumericParameter[int32](
			query.Get("user_id"),
			WithParse[int32](parseInt32),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "user_id", Err: err}, nil)
			return
		}

		userIdParam = param
	} else {
	}
	ctx := r.Context()
	if r.URL.Query().Has("id") {
		ctx = context.WithValue(ctx, "id", r.URL.Query().Get("id"))
	}
	result, err := c.service.GetAllPayments(ctx, userIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// CreatePayment - Создание нового платежа
func (c *PaymentsAPIController) CreatePayment(w http.ResponseWriter, r *http.Request) {
	var paymentInputParam PaymentInput
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&paymentInputParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertPaymentInputRequired(paymentInputParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertPaymentInputConstraints(paymentInputParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.CreatePayment(r.Context(), paymentInputParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
