// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CinemaAbyss API
 *
 * API спецификация для системы CinemaAbyss, включающая монолит и микросервисы.  Система CinemaAbyss представляет собой платформу для управления фильмами, пользователями, платежами и подписками. Архитектура системы включает монолитное приложение и выделенные микросервисы. 
 *
 * API version: 1.0.0
 * Contact: support@cinemaabyss.com
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"
)

// SubscriptionsAPIController binds http requests to an api service and writes the service results to the http response
type SubscriptionsAPIController struct {
	service SubscriptionsAPIServicer
	errorHandler ErrorHandler
}

// SubscriptionsAPIOption for how the controller is set up.
type SubscriptionsAPIOption func(*SubscriptionsAPIController)

// WithSubscriptionsAPIErrorHandler inject ErrorHandler into controller
func WithSubscriptionsAPIErrorHandler(h ErrorHandler) SubscriptionsAPIOption {
	return func(c *SubscriptionsAPIController) {
		c.errorHandler = h
	}
}

// NewSubscriptionsAPIController creates a default api controller
func NewSubscriptionsAPIController(s SubscriptionsAPIServicer, opts ...SubscriptionsAPIOption) *SubscriptionsAPIController {
	controller := &SubscriptionsAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the SubscriptionsAPIController
func (c *SubscriptionsAPIController) Routes() Routes {
	return Routes{
		"GetAllSubscriptions": Route{
			"GetAllSubscriptions",
			strings.ToUpper("Get"),
			"/api/subscriptions",
			c.GetAllSubscriptions,
		},
		"CreateSubscription": Route{
			"CreateSubscription",
			strings.ToUpper("Post"),
			"/api/subscriptions",
			c.CreateSubscription,
		},
	}
}

// OrderedRoutes returns all the api routes in a deterministic order for the SubscriptionsAPIController
func (c *SubscriptionsAPIController) OrderedRoutes() []Route {
	return []Route{
		Route{
			"GetAllSubscriptions",
			strings.ToUpper("Get"),
			"/api/subscriptions",
			c.GetAllSubscriptions,
		},
		Route{
			"CreateSubscription",
			strings.ToUpper("Post"),
			"/api/subscriptions",
			c.CreateSubscription,
		},
	}
}



// GetAllSubscriptions - Получение списка всех подписок
func (c *SubscriptionsAPIController) GetAllSubscriptions(w http.ResponseWriter, r *http.Request) {
	query, err := parseQuery(r.URL.RawQuery)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	var userIdParam int32
	if query.Has("user_id") {
		param, err := parseNumericParameter[int32](
			query.Get("user_id"),
			WithParse[int32](parseInt32),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "user_id", Err: err}, nil)
			return
		}

		userIdParam = param
	} else {
	}
	result, err := c.service.GetAllSubscriptions(r.Context(), userIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// CreateSubscription - Создание новой подписки
func (c *SubscriptionsAPIController) CreateSubscription(w http.ResponseWriter, r *http.Request) {
	var subscriptionInputParam SubscriptionInput
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&subscriptionInputParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertSubscriptionInputRequired(subscriptionInputParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertSubscriptionInputConstraints(subscriptionInputParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.CreateSubscription(r.Context(), subscriptionInputParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
