// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CinemaAbyss API
 *
 * API спецификация для системы CinemaAbyss, включающая монолит и микросервисы.  Система CinemaAbyss представляет собой платформу для управления фильмами, пользователями, платежами и подписками. Архитектура системы включает монолитное приложение и выделенные микросервисы. 
 *
 * API version: 1.0.0
 * Contact: support@cinemaabyss.com
 */

package openapi

import (
	"net/http"
	"strings"
)

// HealthAPIController binds http requests to an api service and writes the service results to the http response
type HealthAPIController struct {
	service HealthAPIServicer
	errorHandler ErrorHandler
}

// HealthAPIOption for how the controller is set up.
type HealthAPIOption func(*HealthAPIController)

// WithHealthAPIErrorHandler inject ErrorHandler into controller
func WithHealthAPIErrorHandler(h ErrorHandler) HealthAPIOption {
	return func(c *HealthAPIController) {
		c.errorHandler = h
	}
}

// NewHealthAPIController creates a default api controller
func NewHealthAPIController(s HealthAPIServicer, opts ...HealthAPIOption) *HealthAPIController {
	controller := &HealthAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the HealthAPIController
func (c *HealthAPIController) Routes() Routes {
	return Routes{
		"GetProxyHealth": Route{
			"GetProxyHealth",
			strings.ToUpper("Get"),
			"/health",
			c.GetProxyHealth,
		},
		"GetMoviesServiceHealth": Route{
			"GetMoviesServiceHealth",
			strings.ToUpper("Get"),
			"/api/movies/health",
			c.GetMoviesServiceHealth,
		},
		"GetEventsServiceHealth": Route{
			"GetEventsServiceHealth",
			strings.ToUpper("Get"),
			"/api/events/health",
			c.GetEventsServiceHealth,
		},
	}
}

// OrderedRoutes returns all the api routes in a deterministic order for the HealthAPIController
func (c *HealthAPIController) OrderedRoutes() []Route {
	return []Route{
		Route{
			"GetProxyHealth",
			strings.ToUpper("Get"),
			"/health",
			c.GetProxyHealth,
		},
		Route{
			"GetMoviesServiceHealth",
			strings.ToUpper("Get"),
			"/api/movies/health",
			c.GetMoviesServiceHealth,
		},
		Route{
			"GetEventsServiceHealth",
			strings.ToUpper("Get"),
			"/api/events/health",
			c.GetEventsServiceHealth,
		},
	}
}



// GetProxyHealth - Проверка работоспособности API Gateway
func (c *HealthAPIController) GetProxyHealth(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.GetProxyHealth(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// GetMoviesServiceHealth - Проверка работоспособности микросервиса фильмов
func (c *HealthAPIController) GetMoviesServiceHealth(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.GetMoviesServiceHealth(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// GetEventsServiceHealth - Проверка работоспособности микросервиса событий
func (c *HealthAPIController) GetEventsServiceHealth(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.GetEventsServiceHealth(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
