// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CinemaAbyss API
 *
 * API спецификация для системы CinemaAbyss, включающая монолит и микросервисы.  Система CinemaAbyss представляет собой платформу для управления фильмами, пользователями, платежами и подписками. Архитектура системы включает монолитное приложение и выделенные микросервисы. 
 *
 * API version: 1.0.0
 * Contact: support@cinemaabyss.com
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"
)

// EventsAPIController binds http requests to an api service and writes the service results to the http response
type EventsAPIController struct {
	service EventsAPIServicer
	errorHandler ErrorHandler
}

// EventsAPIOption for how the controller is set up.
type EventsAPIOption func(*EventsAPIController)

// WithEventsAPIErrorHandler inject ErrorHandler into controller
func WithEventsAPIErrorHandler(h ErrorHandler) EventsAPIOption {
	return func(c *EventsAPIController) {
		c.errorHandler = h
	}
}

// NewEventsAPIController creates a default api controller
func NewEventsAPIController(s EventsAPIServicer, opts ...EventsAPIOption) *EventsAPIController {
	controller := &EventsAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the EventsAPIController
func (c *EventsAPIController) Routes() Routes {
	return Routes{
		"CreateMovieEvent": Route{
			"CreateMovieEvent",
			strings.ToUpper("Post"),
			"/api/events/movie",
			c.CreateMovieEvent,
		},
		"CreateUserEvent": Route{
			"CreateUserEvent",
			strings.ToUpper("Post"),
			"/api/events/user",
			c.CreateUserEvent,
		},
		"CreatePaymentEvent": Route{
			"CreatePaymentEvent",
			strings.ToUpper("Post"),
			"/api/events/payment",
			c.CreatePaymentEvent,
		},
	}
}

// OrderedRoutes returns all the api routes in a deterministic order for the EventsAPIController
func (c *EventsAPIController) OrderedRoutes() []Route {
	return []Route{
		Route{
			"CreateMovieEvent",
			strings.ToUpper("Post"),
			"/api/events/movie",
			c.CreateMovieEvent,
		},
		Route{
			"CreateUserEvent",
			strings.ToUpper("Post"),
			"/api/events/user",
			c.CreateUserEvent,
		},
		Route{
			"CreatePaymentEvent",
			strings.ToUpper("Post"),
			"/api/events/payment",
			c.CreatePaymentEvent,
		},
	}
}



// CreateMovieEvent - Создание события фильма
func (c *EventsAPIController) CreateMovieEvent(w http.ResponseWriter, r *http.Request) {
	var movieEventParam MovieEvent
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&movieEventParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertMovieEventRequired(movieEventParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertMovieEventConstraints(movieEventParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.CreateMovieEvent(r.Context(), movieEventParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// CreateUserEvent - Создание события пользователя
func (c *EventsAPIController) CreateUserEvent(w http.ResponseWriter, r *http.Request) {
	var userEventParam UserEvent
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&userEventParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertUserEventRequired(userEventParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertUserEventConstraints(userEventParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.CreateUserEvent(r.Context(), userEventParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// CreatePaymentEvent - Создание события платежа
func (c *EventsAPIController) CreatePaymentEvent(w http.ResponseWriter, r *http.Request) {
	var paymentEventParam PaymentEvent
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&paymentEventParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertPaymentEventRequired(paymentEventParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertPaymentEventConstraints(paymentEventParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.CreatePaymentEvent(r.Context(), paymentEventParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
