// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CinemaAbyss API
 *
 * API спецификация для системы CinemaAbyss, включающая монолит и микросервисы.  Система CinemaAbyss представляет собой платформу для управления фильмами, пользователями, платежами и подписками. Архитектура системы включает монолитное приложение и выделенные микросервисы.
 *
 * API version: 1.0.0
 * Contact: support@cinemaabyss.com
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"
)

// MoviesAPIController binds http requests to an api service and writes the service results to the http response
type MoviesAPIController struct {
	service      MoviesAPIServicer
	errorHandler ErrorHandler
}

// MoviesAPIOption for how the controller is set up.
type MoviesAPIOption func(*MoviesAPIController)

// WithMoviesAPIErrorHandler inject ErrorHandler into controller
func WithMoviesAPIErrorHandler(h ErrorHandler) MoviesAPIOption {
	return func(c *MoviesAPIController) {
		c.errorHandler = h
	}
}

// NewMoviesAPIController creates a default api controller
func NewMoviesAPIController(s MoviesAPIServicer, opts ...MoviesAPIOption) *MoviesAPIController {
	controller := &MoviesAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the MoviesAPIController
func (c *MoviesAPIController) Routes() Routes {
	return Routes{
		"GetAllMovies": Route{
			"GetAllMovies",
			strings.ToUpper("Get"),
			"/api/movies",
			c.GetAllMovies,
		},
		"CreateMovie": Route{
			"CreateMovie",
			strings.ToUpper("Post"),
			"/api/movies",
			c.CreateMovie,
		},
	}
}

// OrderedRoutes returns all the api routes in a deterministic order for the MoviesAPIController
func (c *MoviesAPIController) OrderedRoutes() []Route {
	return []Route{
		Route{
			"GetAllMovies",
			strings.ToUpper("Get"),
			"/api/movies",
			c.GetAllMovies,
		},
		Route{
			"CreateMovie",
			strings.ToUpper("Post"),
			"/api/movies",
			c.CreateMovie,
		},
	}
}

// GetAllMovies - Получение списка всех фильмов
func (c *MoviesAPIController) GetAllMovies(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.GetAllMovies(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// CreateMovie - Создание нового фильма
func (c *MoviesAPIController) CreateMovie(w http.ResponseWriter, r *http.Request) {
	var movieInputParam MovieInput
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&movieInputParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertMovieInputRequired(movieInputParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertMovieInputConstraints(movieInputParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.CreateMovie(r.Context(), movieInputParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
