// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CinemaAbyss API
 *
 * API спецификация для системы CinemaAbyss, включающая монолит и микросервисы.  Система CinemaAbyss представляет собой платформу для управления фильмами, пользователями, платежами и подписками. Архитектура системы включает монолитное приложение и выделенные микросервисы. 
 *
 * API version: 1.0.0
 * Contact: support@cinemaabyss.com
 */

package openapi




type PaymentInput struct {

	// Идентификатор пользователя, совершающего платеж
	UserId int32 `json:"user_id"`

	// Сумма платежа
	Amount float32 `json:"amount"`
}

// AssertPaymentInputRequired checks if the required fields are not zero-ed
func AssertPaymentInputRequired(obj PaymentInput) error {
	elements := map[string]interface{}{
		"user_id": obj.UserId,
		"amount": obj.Amount,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertPaymentInputConstraints checks if the values respects the defined constraints
func AssertPaymentInputConstraints(obj PaymentInput) error {
	return nil
}
