// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CinemaAbyss API
 *
 * API спецификация для системы CinemaAbyss, включающая монолит и микросервисы.  Система CinemaAbyss представляет собой платформу для управления фильмами, пользователями, платежами и подписками. Архитектура системы включает монолитное приложение и выделенные микросервисы. 
 *
 * API version: 1.0.0
 * Contact: support@cinemaabyss.com
 */

package openapi


import (
	"time"
)



type Event struct {

	// Уникальный идентификатор события
	Id string `json:"id"`

	// Тип события
	Type string `json:"type"`

	// Время события
	Timestamp time.Time `json:"timestamp"`

	// Полезная нагрузка события (зависит от типа события)
	Payload map[string]interface{} `json:"payload"`
}

// AssertEventRequired checks if the required fields are not zero-ed
func AssertEventRequired(obj Event) error {
	elements := map[string]interface{}{
		"id": obj.Id,
		"type": obj.Type,
		"timestamp": obj.Timestamp,
		"payload": obj.Payload,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertEventConstraints checks if the values respects the defined constraints
func AssertEventConstraints(obj Event) error {
	return nil
}
