// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CinemaAbyss API
 *
 * API спецификация для системы CinemaAbyss, включающая монолит и микросервисы.  Система CinemaAbyss представляет собой платформу для управления фильмами, пользователями, платежами и подписками. Архитектура системы включает монолитное приложение и выделенные микросервисы. 
 *
 * API version: 1.0.0
 * Contact: support@cinemaabyss.com
 */

package openapi


import (
	"time"
)



type Payment struct {

	// Уникальный идентификатор платежа
	Id int32 `json:"id"`

	// Идентификатор пользователя, совершившего платеж
	UserId int32 `json:"user_id"`

	// Сумма платежа
	Amount float32 `json:"amount"`

	// Время совершения платежа
	Timestamp time.Time `json:"timestamp"`
}

// AssertPaymentRequired checks if the required fields are not zero-ed
func AssertPaymentRequired(obj Payment) error {
	elements := map[string]interface{}{
		"id": obj.Id,
		"user_id": obj.UserId,
		"amount": obj.Amount,
		"timestamp": obj.Timestamp,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertPaymentConstraints checks if the values respects the defined constraints
func AssertPaymentConstraints(obj Payment) error {
	return nil
}
