// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CinemaAbyss API
 *
 * API спецификация для системы CinemaAbyss, включающая монолит и микросервисы.  Система CinemaAbyss представляет собой платформу для управления фильмами, пользователями, платежами и подписками. Архитектура системы включает монолитное приложение и выделенные микросервисы. 
 *
 * API version: 1.0.0
 * Contact: support@cinemaabyss.com
 */

package openapi




type EventResponse struct {

	// Статус операции
	Status string `json:"status"`

	// Партиция Kafka
	Partition int32 `json:"partition"`

	// Смещение в партиции Kafka
	Offset int32 `json:"offset"`

	Event Event `json:"event"`
}

// AssertEventResponseRequired checks if the required fields are not zero-ed
func AssertEventResponseRequired(obj EventResponse) error {
	elements := map[string]interface{}{
		"status": obj.Status,
		"partition": obj.Partition,
		"offset": obj.Offset,
		"event": obj.Event,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertEventRequired(obj.Event); err != nil {
		return err
	}
	return nil
}

// AssertEventResponseConstraints checks if the values respects the defined constraints
func AssertEventResponseConstraints(obj EventResponse) error {
	if err := AssertEventConstraints(obj.Event); err != nil {
		return err
	}
	return nil
}
