// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CinemaAbyss API
 *
 * API спецификация для системы CinemaAbyss, включающая монолит и микросервисы.  Система CinemaAbyss представляет собой платформу для управления фильмами, пользователями, платежами и подписками. Архитектура системы включает монолитное приложение и выделенные микросервисы. 
 *
 * API version: 1.0.0
 * Contact: support@cinemaabyss.com
 */

package openapi




type MovieInput struct {

	// Название фильма
	Title string `json:"title"`

	// Описание фильма
	Description string `json:"description"`

	// Жанры фильма
	Genres []string `json:"genres,omitempty"`

	// Рейтинг фильма
	Rating float32 `json:"rating"`
}

// AssertMovieInputRequired checks if the required fields are not zero-ed
func AssertMovieInputRequired(obj MovieInput) error {
	elements := map[string]interface{}{
		"title": obj.Title,
		"description": obj.Description,
		"rating": obj.Rating,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertMovieInputConstraints checks if the values respects the defined constraints
func AssertMovieInputConstraints(obj MovieInput) error {
	return nil
}
