// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CinemaAbyss API
 *
 * API спецификация для системы CinemaAbyss, включающая монолит и микросервисы.  Система CinemaAbyss представляет собой платформу для управления фильмами, пользователями, платежами и подписками. Архитектура системы включает монолитное приложение и выделенные микросервисы. 
 *
 * API version: 1.0.0
 * Contact: support@cinemaabyss.com
 */

package openapi


import (
	"time"
)



type SubscriptionInput struct {

	// Идентификатор пользователя, оформляющего подписку
	UserId int32 `json:"user_id"`

	// Тип плана подписки
	PlanType string `json:"plan_type"`

	// Дата начала подписки
	StartDate time.Time `json:"start_date"`

	// Дата окончания подписки
	EndDate time.Time `json:"end_date"`
}

// AssertSubscriptionInputRequired checks if the required fields are not zero-ed
func AssertSubscriptionInputRequired(obj SubscriptionInput) error {
	elements := map[string]interface{}{
		"user_id": obj.UserId,
		"plan_type": obj.PlanType,
		"start_date": obj.StartDate,
		"end_date": obj.EndDate,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertSubscriptionInputConstraints checks if the values respects the defined constraints
func AssertSubscriptionInputConstraints(obj SubscriptionInput) error {
	return nil
}
