// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CinemaAbyss API
 *
 * API спецификация для системы CinemaAbyss, включающая монолит и микросервисы.  Система CinemaAbyss представляет собой платформу для управления фильмами, пользователями, платежами и подписками. Архитектура системы включает монолитное приложение и выделенные микросервисы. 
 *
 * API version: 1.0.0
 * Contact: support@cinemaabyss.com
 */

package openapi




type GetMoviesServiceHealth200Response struct {

	Status bool `json:"status,omitempty"`
}

// AssertGetMoviesServiceHealth200ResponseRequired checks if the required fields are not zero-ed
func AssertGetMoviesServiceHealth200ResponseRequired(obj GetMoviesServiceHealth200Response) error {
	return nil
}

// AssertGetMoviesServiceHealth200ResponseConstraints checks if the values respects the defined constraints
func AssertGetMoviesServiceHealth200ResponseConstraints(obj GetMoviesServiceHealth200Response) error {
	return nil
}
