apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJjSEpwYldGcmFXNDZaMmh3WDNCM1FVaHpkVU5LVm10bGNrMWhaakJ6YzJOV1NVZzBkblJRU2tnNFpqSjNObEpVZFE9PSIKICAgIH0KICB9Cn0=
type: kubernetes.io/dockerconfigjson
